### ISSUE TITLE
optimize gitlab CI

### ISSUE THREAD

**Issue by simevo** [simevo/flash#29]
1. pre-commit:
```
precommit:
  stage: lint
  image: python:3.12
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - pip install -q pre-commit
  script:
    - pre-commit run --show-diff-on-failure --color=always --all-files
```
2. move prepare to lint
3. move test-frontend to lint-javascript and rename stage to ... ?
4. add artifacts to backend-test
